import { defineCommand } from "citty";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { parse, decrypt, isEncrypted, resolveValue } from "@vars/core";
import { buildContext, requireKey, getKeyFromEnv, findVarsFile } from "../utils/context.js";
import { promptSelect } from "../utils/prompt.js";
import * as output from "../utils/output.js";

/**
 * Collect all unique environment names from a parsed .vars file.
 * Excludes "default" since it's a fallback, not a selectable environment.
 */
export function listEnvironments(filePath: string): string[] {
  const content = readFileSync(filePath, "utf8");
  const parsed = parse(content, filePath);
  const envSet = new Set<string>();
  for (const v of parsed.variables) {
    for (const val of v.values) {
      if (val.env !== "default") {
        envSet.add(val.env);
      }
    }
  }
  return [...envSet].sort();
}

export default defineCommand({
  meta: {
    name: "export",
    description: "Export decrypted vars as .env format to stdout",
  },
  args: {
    env: {
      type: "string",
      description: "Environment to export",
    },
    file: {
      type: "string",
      description: "Path to .vars file",
      alias: "f",
    },
  },
  async run({ args }) {
    // Two separate TTY checks:
    // canPrompt: whether we can show interactive prompts (needs both stdin + stderr)
    // showChrome: whether we should show clack intro/outro (only needs stderr)
    const canPrompt = process.stdin.isTTY && process.stderr.isTTY;
    const showChrome = !!process.stderr.isTTY;

    // Resolve file path without building full context yet
    const varsFilePath = args.file
      ? resolve(process.cwd(), args.file)
      : findVarsFile() ?? resolve(process.cwd(), ".vars", "vault.vars");

    // Resolve env: flag > interactive picker > "dev" fallback
    let env = args.env;

    if (!env && canPrompt) {
      const envs = listEnvironments(varsFilePath);
      if (envs.length > 0) {
        output.intro("export");
        env = await promptSelect("Select environment", envs);
      } else {
        env = "dev";
      }
    } else if (!env) {
      env = "dev";
    }

    // Build context with resolved env
    const ctx = buildContext({ file: args.file, env });

    // Get key: VARS_KEY env var or interactive PIN prompt
    let key: Buffer | null = getKeyFromEnv();
    if (!key) {
      key = await requireKey(ctx);
    }

    const result = generateExport(ctx.varsFilePath, ctx.env, key);

    process.stdout.write(result);

    if (showChrome) {
      const lineCount = result.split("\n").filter((l) => l && !l.startsWith("#")).length;
      output.outro(`Exported ${lineCount} variable${lineCount !== 1 ? "s" : ""} (@${ctx.env})`);
    }
  },
});

/**
 * Generate a .env-formatted string from a .vars file.
 */
export function generateExport(
  filePath: string,
  env: string,
  key: Buffer | null,
): string {
  const content = readFileSync(filePath, "utf8");
  const parsed = parse(content, filePath);
  const lines: string[] = [];

  lines.push(`# Generated by 'vars export --env ${env}'`);
  lines.push(`# Source: ${filePath}`);
  lines.push("");

  for (const v of parsed.variables) {
    const raw = resolveValue(v, env);
    if (raw === undefined) continue;

    let value = raw;
    if (isEncrypted(value)) {
      if (key) {
        value = decrypt(value, key);
      } else {
        continue;
      }
    }

    if (value.includes(" ") || value.includes("#") || value.includes("=")) {
      lines.push(`${v.name}="${value}"`);
    } else {
      lines.push(`${v.name}=${value}`);
    }
  }

  lines.push("");
  return lines.join("\n");
}
