import { defineCommand } from "citty";
import { existsSync, readFileSync, writeFileSync, appendFileSync } from "node:fs";
import { join, resolve } from "node:path";
import {
  createMasterKey,
  encryptMasterKey,
  encrypt,
} from "@vars/core";
import pc from "picocolors";
import * as output from "../utils/output.js";
import { promptPIN } from "../utils/prompt.js";

export default defineCommand({
  meta: {
    name: "init",
    description: "Initialize a new .vars project from existing .env files",
  },
  args: {
    file: {
      type: "string",
      description: "Path to .env file to import",
      alias: "f",
    },
    env: {
      type: "string",
      description: "Environment name for imported values",
      default: "dev",
    },
  },
  async run({ args }) {
    const cwd = process.cwd();
    const varsPath = resolve(cwd, ".vars");

    if (existsSync(varsPath)) {
      output.warn(".vars already exists. Use 'vars add' to add variables.");
      return;
    }

    output.heading("vars init");
    output.info("Setting up encrypted environment variables...\n");

    console.log(pc.yellow(pc.bold("  ⚠  Important: Your PIN is the only way to decrypt your secrets.")));
    console.log(pc.dim("     There is no recovery mechanism. If you forget it, all encrypted"));
    console.log(pc.dim("     values are lost and must be re-created from scratch.\n"));
    console.log(pc.dim("     Store your PIN somewhere your coding agent can't access:"));
    console.log(pc.dim("       • A password manager (1Password, Bitwarden, etc.)"));
    console.log(pc.dim("       • A team Slack/Discord channel"));
    console.log(pc.dim("       • Written down physically\n"));

    const pin = await promptPIN("Choose a PIN");
    const pinConfirm = await promptPIN("Confirm PIN");
    if (pin !== pinConfirm) {
      output.error("PINs do not match. Aborting.");
      process.exit(1);
    }

    const masterKey = await createMasterKey();
    const encryptedKey = await encryptMasterKey(masterKey, pin);

    const envFilePath = args.file ?? join(cwd, ".env");
    let envVars: Array<{ name: string; value: string }> = [];
    if (existsSync(envFilePath)) {
      output.info(`Found ${envFilePath}, importing variables...`);
      envVars = scanEnvFile(envFilePath);
      output.success(`Scanned ${envVars.length} variables from .env`);
    } else {
      output.info("No .env file found. Creating empty .vars project.");
    }

    const envName = args.env ?? "dev";
    const lines: string[] = ["# Generated by vars init", ""];

    for (const { name, value } of envVars) {
      const schema = inferSchema(name, value);
      const encValue = encrypt(value, masterKey);
      lines.push(`${name}  ${schema}`);
      lines.push(`  @${envName} = ${encValue}`);
      lines.push("");
    }

    if (envVars.length === 0) {
      lines.push("# Add your first variable:");
      lines.push("# PORT  z.coerce.number().int().min(1024).max(65535)");
      lines.push("#   @dev     = 3000");
      lines.push("#   @prod    = 8080");
      lines.push("");
    }

    writeFileSync(varsPath, lines.join("\n"));
    writeFileSync(resolve(cwd, "varskey"), encryptedKey + "\n");
    updateGitignore(cwd);

    output.success("Created .vars (encrypted values)");
    output.success("Created varskey (PIN-protected encryption key)");
  },
});

/**
 * Scan a .env file and return key-value pairs.
 */
export function scanEnvFile(filePath: string): Array<{ name: string; value: string }> {
  const content = readFileSync(filePath, "utf8");
  const vars: Array<{ name: string; value: string }> = [];

  for (const line of content.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;

    const withoutExport = trimmed.startsWith("export ")
      ? trimmed.slice(7)
      : trimmed;

    const eqIdx = withoutExport.indexOf("=");
    if (eqIdx === -1) continue;

    const name = withoutExport.slice(0, eqIdx).trim();
    let value = withoutExport.slice(eqIdx + 1).trim();

    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }

    vars.push({ name, value });
  }

  return vars;
}

/**
 * Infer a Zod schema string from a variable name and sample value.
 */
export function inferSchema(name: string, value: string): string {
  if (/^\d+$/.test(value) || /^\d+\.\d+$/.test(value)) {
    return "z.coerce.number()";
  }

  if (value === "true" || value === "false") {
    return "z.coerce.boolean()";
  }

  if (/^https?:\/\//i.test(value) || /^postgres(ql)?:\/\//i.test(value) || /^redis:\/\//i.test(value) || /^mongodb(\+srv)?:\/\//i.test(value)) {
    return "z.string().url()";
  }

  const nameLower = name.toLowerCase();
  if (nameLower === "log_level" || nameLower === "loglevel") {
    return 'z.enum(["debug", "info", "warn", "error"])';
  }
  if (nameLower === "node_env" || nameLower === "environment" || nameLower === "env") {
    return 'z.enum(["development", "staging", "production", "test"])';
  }

  return "z.string()";
}

/**
 * Non-interactive init for testing.
 */
export async function initProject(options: {
  cwd: string;
  pin: string;
  env: string;
  interactive: boolean;
}): Promise<void> {
  const { cwd, pin, env } = options;
  const varsPath = resolve(cwd, ".vars");
  const keyPath = resolve(cwd, "varskey");

  const masterKey = await createMasterKey();
  const encryptedKey = await encryptMasterKey(masterKey, pin);

  const envFilePath = join(cwd, ".env");
  let envVars: Array<{ name: string; value: string }> = [];
  if (existsSync(envFilePath)) {
    envVars = scanEnvFile(envFilePath);
  }

  const lines: string[] = ["# Generated by vars init", ""];

  for (const { name, value } of envVars) {
    const schema = inferSchema(name, value);
    const encValue = encrypt(value, masterKey);
    lines.push(`${name}  ${schema}`);
    lines.push(`  @${env} = ${encValue}`);
    lines.push("");
  }

  writeFileSync(varsPath, lines.join("\n"));
  writeFileSync(keyPath, encryptedKey + "\n");
  updateGitignore(cwd);
}

function updateGitignore(cwd: string): void {
  const gitignorePath = join(cwd, ".gitignore");
  const varsEntries = [
    "",
    "# vars",
    "varskey",
    "varskey.*",
    ".vars.unlocked",
    ".env",
    ".env.*",
    ".vars.swp",
    ".vars.swo",
    ".vars~",
    ".vars.bak",
  ].join("\n");

  if (existsSync(gitignorePath)) {
    const existing = readFileSync(gitignorePath, "utf8");
    if (!existing.includes("varskey")) {
      appendFileSync(gitignorePath, "\n" + varsEntries + "\n");
    }
  } else {
    writeFileSync(gitignorePath, varsEntries + "\n");
  }
}
