import { defineCommand } from "citty";
import {
  existsSync,
  mkdirSync,
  readFileSync,
  writeFileSync,
  appendFileSync,
  unlinkSync,
} from "node:fs";
import { join, resolve } from "node:path";
import {
  createMasterKey,
  encryptMasterKey,
  encrypt,
} from "@vars/core";
import pc from "picocolors";
import * as clack from "@clack/prompts";
import * as output from "../utils/output.js";
import { promptConfirm, promptPIN } from "../utils/prompt.js";
import { detectFramework } from "../utils/detect-framework.js";
import { installHook } from "./hook.js";

export default defineCommand({
  meta: {
    name: "init",
    description: "Initialize a new .vars project from existing .env files",
  },
  args: {
    file: {
      type: "string",
      description: "Path to .env file to import",
      alias: "f",
    },
    env: {
      type: "string",
      description: "Environment name for imported values",
      default: "dev",
    },
  },
  async run({ args }) {
    const cwd = process.cwd();
    const varsDir = resolve(cwd, ".vars");
    const varsPath = resolve(varsDir, "vault.vars");

    if (existsSync(varsPath)) {
      output.warn(
        ".vars/vault.vars already exists. Use 'vars add' to add variables.",
      );
      return;
    }

    // ── Intro ──────────────────────────────────────────────────────────
    output.intro("init");
    clack.log.message("Setting up encrypted environment variables.");

    // ── PIN entry with mismatch retry loop ─────────────────────────────
    let pin: string;
    for (;;) {
      pin = await promptPIN("Choose a PIN");
      const pinConfirm = await promptPIN("Confirm PIN");
      if (pin === pinConfirm) break;
      output.error("PINs do not match. Try again.");
    }

    // ── PIN warning (shown AFTER both PINs confirmed) ──────────────────
    output.warning("Your PIN is the only way to decrypt your secrets.", [
      "No recovery mechanism — lose it, lose everything",
      "Store it in a password manager, team chat, or written down",
      "Keep it somewhere your coding agent can't access",
    ]);

    // ── Create master key and encrypt it ───────────────────────────────
    const masterKey = await createMasterKey();
    const encryptedKey = await encryptMasterKey(masterKey, pin);

    // ── Import .env variables ──────────────────────────────────────────
    const envFilePath = args.file ?? join(cwd, ".env");
    let envVars: Array<{ name: string; value: string }> = [];

    if (existsSync(envFilePath)) {
      const s = clack.spinner();
      envVars = scanEnvFile(envFilePath);
      s.start(`Importing ${envVars.length} variables from .env...`);

      const envName = args.env ?? "dev";
      const lines: string[] = ["# Generated by vars init", ""];

      for (const { name, value } of envVars) {
        const schema = inferSchema(name, value);
        const encValue = encrypt(value, masterKey);
        lines.push(`${name}  ${schema}`);
        lines.push(`  @${envName} = ${encValue}`);
        lines.push("");
      }

      mkdirSync(varsDir, { recursive: true });
      writeFileSync(varsPath, lines.join("\n"));
      writeFileSync(resolve(varsDir, "key"), encryptedKey + "\n");
      updateGitignore(cwd);

      s.stop(`Imported ${envVars.length} variables from .env`);
    } else {
      clack.log.info("No .env file found. Creating empty .vars project.");

      const lines: string[] = [
        "# Generated by vars init",
        "",
        "# Add your first variable:",
        "# PORT  z.coerce.number().int().min(1024).max(65535)",
        "#   @dev     = 3000",
        "#   @prod    = 8080",
        "",
      ];

      mkdirSync(varsDir, { recursive: true });
      writeFileSync(varsPath, lines.join("\n"));
      writeFileSync(resolve(varsDir, "key"), encryptedKey + "\n");
      updateGitignore(cwd);
    }

    // ── Delete .env prompt ─────────────────────────────────────────────
    if (envVars.length > 0 && existsSync(envFilePath)) {
      const shouldDelete = await promptConfirm(
        "Delete .env? (plaintext secrets are now encrypted)",
      );
      if (shouldDelete) {
        unlinkSync(envFilePath);
      }
    }

    // ── Hook installation prompt ───────────────────────────────────────
    let hookInstalled = false;
    const shouldInstallHook = await promptConfirm(
      "Install pre-commit hook? (blocks commits if secrets are decrypted)",
    );
    if (shouldInstallHook) {
      try {
        installHook(cwd);
        hookInstalled = true;
      } catch {
        // No .git directory or other issue — skip gracefully
      }
    }

    // ── File tree ──────────────────────────────────────────────────────
    clack.log.message(pc.bold("Created:"));
    output.fileTree(".vars/", [
      { path: "vault.vars", description: "Encrypted secrets (commit this)" },
      {
        path: "key",
        description: "PIN-protected master key (gitignored)",
      },
      {
        path: "unlocked.vars",
        description: "Only exists during editing (gitignored)",
      },
    ]);

    clack.log.message(
      [
        pc.bold("Also generates:"),
        `└── vars.generated.ts   ${pc.dim("— Typed accessors, auto-regenerated")}`,
      ].join("\n"),
    );

    // ── Safety checks ──────────────────────────────────────────────────
    output.safetyChecks([
      {
        label: ".gitignore updated — key and unlocked.vars won't be committed",
        status: "pass",
      },
      {
        label: hookInstalled
          ? "Pre-commit hook installed — blocks commits with decrypted secrets"
          : "Pre-commit hook not installed",
        status: hookInstalled ? "pass" : "warn",
        fix: hookInstalled
          ? undefined
          : "Run 'vars hook install' to add it later",
      },
    ]);

    // ── Framework detection ────────────────────────────────────────────
    const framework = detectFramework(cwd);
    if (framework) {
      const snippetLines = framework.snippet.split("\n");
      const boxContent = snippetLines
        .map((line) => `│  ${line}`)
        .join("\n");

      clack.log.message(
        [
          `Detected: ${pc.bold(framework.name)}`,
          `┌  Add to ${framework.configFile}:`,
          boxContent,
          `└  Run: pnpm add ${framework.package}`,
        ].join("\n"),
      );
    }

    // ── Workflow ────────────────────────────────────────────────────────
    clack.log.message(
      [
        pc.bold("Workflow:"),
        `1. ${pc.cyan("vars show")}   → decrypt (vault.vars → unlocked.vars)`,
        `2. Edit unlocked.vars`,
        `3. ${pc.cyan("vars hide")}   → re-encrypt (unlocked.vars → vault.vars)`,
      ].join("\n"),
    );

    // ── Outro ──────────────────────────────────────────────────────────
    output.outro("Ready! Run vars show to start editing.");
  },
});

/**
 * Scan a .env file and return key-value pairs.
 */
export function scanEnvFile(
  filePath: string,
): Array<{ name: string; value: string }> {
  const content = readFileSync(filePath, "utf8");
  const vars: Array<{ name: string; value: string }> = [];

  for (const line of content.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;

    const withoutExport = trimmed.startsWith("export ")
      ? trimmed.slice(7)
      : trimmed;

    const eqIdx = withoutExport.indexOf("=");
    if (eqIdx === -1) continue;

    const name = withoutExport.slice(0, eqIdx).trim();
    let value = withoutExport.slice(eqIdx + 1).trim();

    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }

    vars.push({ name, value });
  }

  return vars;
}

/**
 * Infer a Zod schema string from a variable name and sample value.
 */
export function inferSchema(name: string, value: string): string {
  if (/^\d+$/.test(value) || /^\d+\.\d+$/.test(value)) {
    return "z.coerce.number()";
  }

  if (value === "true" || value === "false") {
    return "z.coerce.boolean()";
  }

  if (
    /^https?:\/\//i.test(value) ||
    /^postgres(ql)?:\/\//i.test(value) ||
    /^redis:\/\//i.test(value) ||
    /^mongodb(\+srv)?:\/\//i.test(value)
  ) {
    return "z.string().url()";
  }

  const nameLower = name.toLowerCase();
  if (nameLower === "log_level" || nameLower === "loglevel") {
    return 'z.enum(["debug", "info", "warn", "error"])';
  }
  if (
    nameLower === "node_env" ||
    nameLower === "environment" ||
    nameLower === "env"
  ) {
    return 'z.enum(["development", "staging", "production", "test"])';
  }

  return "z.string()";
}

/**
 * Non-interactive init for testing.
 */
export async function initProject(options: {
  cwd: string;
  pin: string;
  env: string;
  interactive: boolean;
}): Promise<void> {
  const { cwd, pin, env } = options;
  const varsDir = resolve(cwd, ".vars");
  const varsPath = resolve(varsDir, "vault.vars");
  const keyPath = resolve(varsDir, "key");

  const masterKey = await createMasterKey();
  const encryptedKey = await encryptMasterKey(masterKey, pin);

  const envFilePath = join(cwd, ".env");
  let envVars: Array<{ name: string; value: string }> = [];
  if (existsSync(envFilePath)) {
    envVars = scanEnvFile(envFilePath);
  }

  const lines: string[] = ["# Generated by vars init", ""];

  for (const { name, value } of envVars) {
    const schema = inferSchema(name, value);
    const encValue = encrypt(value, masterKey);
    lines.push(`${name}  ${schema}`);
    lines.push(`  @${env} = ${encValue}`);
    lines.push("");
  }

  mkdirSync(varsDir, { recursive: true });
  writeFileSync(varsPath, lines.join("\n"));
  writeFileSync(keyPath, encryptedKey + "\n");
  updateGitignore(cwd);
}

function updateGitignore(cwd: string): void {
  const gitignorePath = join(cwd, ".gitignore");
  const varsEntries = [
    "",
    "# vars",
    ".vars/key",
    ".vars/key.*",
    ".vars/unlocked.vars",
    ".env",
    ".env.*",
    ".vars.swp",
    ".vars.swo",
    ".vars~",
    ".vars.bak",
  ].join("\n");

  if (existsSync(gitignorePath)) {
    const existing = readFileSync(gitignorePath, "utf8");
    if (!existing.includes(".vars/key")) {
      appendFileSync(gitignorePath, "\n" + varsEntries + "\n");
    }
  } else {
    writeFileSync(gitignorePath, varsEntries + "\n");
  }
}
