import { defineCommand } from "citty";
import { readFileSync } from "node:fs";
import { parse, decrypt, isEncrypted, retrieveKey, resolveValue } from "@vars/core";
import { buildContext, getMasterKeyFromEnv } from "../utils/context.js";

export default defineCommand({
  meta: {
    name: "template",
    description: "Generate a .env file from .vars (for Docker, legacy tools)",
  },
  args: {
    env: {
      type: "string",
      description: "Environment to export",
      default: "dev",
    },
    file: {
      type: "string",
      description: "Path to .vars file",
      alias: "f",
    },
  },
  async run({ args }) {
    const ctx = buildContext({ file: args.file, env: args.env });

    let key: Buffer | null = null;
    try {
      key = getMasterKeyFromEnv();
      if (!key) {
        key = await retrieveKey();
      }
    } catch {
      // No key available
    }

    const result = generateTemplate(ctx.varsFilePath, ctx.env, key);
    process.stdout.write(result);
  },
});

/**
 * Generate a .env-formatted string from a .vars file.
 */
export function generateTemplate(
  filePath: string,
  env: string,
  key: Buffer | null,
): string {
  const content = readFileSync(filePath, "utf8");
  const parsed = parse(content, filePath);
  const lines: string[] = [];

  lines.push(`# Generated by 'vars template --env ${env}'`);
  lines.push(`# Source: ${filePath}`);
  lines.push("");

  for (const v of parsed.variables) {
    const raw = resolveValue(v, env);
    if (raw === undefined) continue;

    let value = raw;
    if (isEncrypted(value)) {
      if (key) {
        value = decrypt(value, key);
      } else {
        continue;
      }
    }

    if (value.includes(" ") || value.includes("#") || value.includes("=")) {
      lines.push(`${v.name}="${value}"`);
    } else {
      lines.push(`${v.name}=${value}`);
    }
  }

  lines.push("");
  return lines.join("\n");
}
