import { defineCommand } from "citty";
import { readFileSync } from "node:fs";
import { parse, decrypt, isEncrypted, resolveValue } from "@vars/core";
import { buildContext, getKeyFromEnv } from "../utils/context.js";
import * as output from "../utils/output.js";

export default defineCommand({
  meta: {
    name: "template",
    description: "Generate a .env file from .vars (for Docker, legacy tools)",
  },
  args: {
    env: {
      type: "string",
      description: "Environment to export",
      default: "dev",
    },
    file: {
      type: "string",
      description: "Path to .vars file",
      alias: "f",
    },
  },
  async run({ args }) {
    const ctx = buildContext({ file: args.file, env: args.env });
    const key = getKeyFromEnv();
    const result = generateTemplate(ctx.varsFilePath, ctx.env, key);

    // Output goes to stdout for piping (vars template > .env)
    // Clack intro/outro goes to stderr so it doesn't pollute the pipe
    const isTTY = process.stderr.isTTY;
    if (isTTY) {
      output.intro("template");
    }

    process.stdout.write(result);

    if (isTTY) {
      const lineCount = result.split("\n").filter((l) => l && !l.startsWith("#")).length;
      output.outro(`Generated .env with ${lineCount} variable${lineCount !== 1 ? "s" : ""} (@${ctx.env})`);
    }
  },
});

/**
 * Generate a .env-formatted string from a .vars file.
 */
export function generateTemplate(
  filePath: string,
  env: string,
  key: Buffer | null,
): string {
  const content = readFileSync(filePath, "utf8");
  const parsed = parse(content, filePath);
  const lines: string[] = [];

  lines.push(`# Generated by 'vars template --env ${env}'`);
  lines.push(`# Source: ${filePath}`);
  lines.push("");

  for (const v of parsed.variables) {
    const raw = resolveValue(v, env);
    if (raw === undefined) continue;

    let value = raw;
    if (isEncrypted(value)) {
      if (key) {
        value = decrypt(value, key);
      } else {
        continue;
      }
    }

    if (value.includes(" ") || value.includes("#") || value.includes("=")) {
      lines.push(`${v.name}="${value}"`);
    } else {
      lines.push(`${v.name}=${value}`);
    }
  }

  lines.push("");
  return lines.join("\n");
}
