import { describe, it, expect } from "vitest";
import { resolveUseChain } from "../use-resolver.js";
import { createMasterKey } from "../key-manager.js";
import { showFile, hideFile } from "../show-hide.js";
import { generateTypeScript, validateValue, evaluateCheck, parse } from "@vars/core";
import { resolve, join } from "node:path";
import { writeFileSync, readFileSync, mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { fileURLToPath } from "node:url";
import { dirname } from "node:path";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const fixtureDir = resolve(__dirname, "fixtures");

describe("full pipeline integration", () => {
  it("parse → resolve → validate → codegen end-to-end", () => {
    const resolved = resolveUseChain(
      resolve(fixtureDir, "services/api/vars.vars"),
      { env: "dev" },
    );

    // All vars resolved
    expect(resolved.vars.length).toBeGreaterThanOrEqual(4);

    // Validate each variable's value against its schema
    for (const v of resolved.vars) {
      if (v.value !== undefined) {
        const result = validateValue(v.schema, v.value);
        expect(result.success).toBe(true);
      }
    }

    // Generate TypeScript
    const code = generateTypeScript(resolved);
    expect(code).toContain("@generated by vars");
    expect(code).toContain("APP_NAME: string"); // public
    expect(code).toContain("API_KEY: Redacted<string>"); // secret
    expect(code).toContain("parseVars(process.env)");
  });

  it("encrypt → decrypt roundtrip preserves file", async () => {
    const dir = mkdtempSync(join(tmpdir(), "vars-int-"));
    const key = await createMasterKey();

    const content = `# @vars-state unlocked
env(dev, prod)

public APP_NAME = "test-app"
SECRET : z.string() {
  dev  = "dev-secret-value"
  prod = "prod-secret-value"
}`;

    const filePath = join(dir, "config.vars");
    writeFileSync(filePath, content);

    // Hide (encrypt)
    hideFile(filePath, key);
    const encrypted = readFileSync(filePath, "utf8");
    expect(encrypted).toContain("# @vars-state locked");
    expect(encrypted).not.toContain("dev-secret-value");
    expect(encrypted).not.toContain("prod-secret-value");
    expect(encrypted).toContain('APP_NAME = "test-app"'); // public unchanged

    // Show (decrypt)
    showFile(filePath, key);
    const decrypted = readFileSync(filePath, "utf8");
    expect(decrypted).toContain("# @vars-state unlocked");
    expect(decrypted).toContain("dev-secret-value");
    expect(decrypted).toContain("prod-secret-value");

    rmSync(dir, { recursive: true });
  });

  it("deterministic encryption produces stable diffs", async () => {
    const dir = mkdtempSync(join(tmpdir(), "vars-det-"));
    const key = await createMasterKey();

    const content = `# @vars-state unlocked
env(dev)

SECRET : z.string() {
  dev = "stable-value"
}`;

    const filePath = join(dir, "config.vars");
    writeFileSync(filePath, content);

    // First hide
    hideFile(filePath, key);
    const first = readFileSync(filePath, "utf8");

    // Show + hide again (no changes)
    showFile(filePath, key);
    hideFile(filePath, key);
    const second = readFileSync(filePath, "utf8");

    // Deterministic: identical output
    expect(first).toBe(second);

    rmSync(dir, { recursive: true });
  });

  it("codegen with different platforms", () => {
    const resolved = resolveUseChain(
      resolve(fixtureDir, "services/api/vars.vars"),
      { env: "dev" },
    );

    const nodeCode = generateTypeScript(resolved, { platform: "node" });
    expect(nodeCode).toContain("process.env");

    const cfCode = generateTypeScript(resolved, { platform: "cloudflare" });
    expect(cfCode).toContain("getVars");
    expect(cfCode).not.toContain("process.env");

    const denoCode = generateTypeScript(resolved, { platform: "deno" });
    expect(denoCode).toContain("Deno.env");
  });

  it("multi-file use chain resolves all variables", () => {
    const resolved = resolveUseChain(
      resolve(fixtureDir, "services/api/vars.vars"),
      { env: "prod" },
    );

    // Should have vars from both child and parent
    const names = resolved.vars.map(v => v.name);
    expect(names).toContain("APP_NAME"); // child
    expect(names).toContain("API_KEY"); // child
    expect(names).toContain("LOG_LEVEL"); // from shared via use
    expect(names).toContain("SHARED_SECRET"); // from shared via use

    // Values should be prod values
    const apiKey = resolved.vars.find(v => v.name === "API_KEY");
    expect(apiKey?.value).toBe("prod-key");
  });

  it("check evaluator works with resolved vars", () => {
    const src = `env(dev, prod)
DEBUG : z.boolean() = false
LOG_LEVEL : z.enum(["debug", "info", "warn", "error"]) = "info" {
  dev = "debug"
}

check "No debug in prod" {
  env == "prod" => LOG_LEVEL != "debug"
}`;

    const result = parse(src);
    const check = result.ast.checks[0];
    expect(check).toBeDefined();
    expect(check!.predicates.length).toBeGreaterThan(0);

    const predicate = check!.predicates[0]!;

    // Prod: LOG_LEVEL = "info" (default), env = "prod"
    // "prod" == "prod" => "info" != "debug" → true
    expect(evaluateCheck(predicate, { LOG_LEVEL: "info", DEBUG: "false" }, "prod", {})).toBe(true);

    // Dev: LOG_LEVEL = "debug", env = "dev"
    // "dev" == "prod" is false → vacuously true
    expect(evaluateCheck(predicate, { LOG_LEVEL: "debug", DEBUG: "false" }, "dev", {})).toBe(true);
  });
});
