import { randomBytes } from "node:crypto";
import { mkdtempSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, expect, it, beforeEach } from "vitest";
import { encrypt } from "@vars/core";
import { generateExport, listEnvironments } from "../../commands/export.js";

describe("vars export", () => {
  let tmpDir: string;
  let key: Buffer;

  beforeEach(() => {
    tmpDir = mkdtempSync(join(tmpdir(), "vars-export-test-"));
    key = randomBytes(32);
  });

  it("generates a .env-style output from plaintext .vars", () => {
    writeFileSync(
      join(tmpDir, ".vars"),
      [
        "PORT  z.coerce.number()",
        "  @default = 3000",
        "  @prod    = 8080",
        "",
        "HOST  z.string()",
        "  @default = localhost",
      ].join("\n"),
    );

    const result = generateExport(join(tmpDir, ".vars"), "dev", null);
    expect(result).toContain("PORT=3000");
    expect(result).toContain("HOST=localhost");
  });

  it("decrypts encrypted values when key is provided", () => {
    const encPort = encrypt("8080", key);
    writeFileSync(
      join(tmpDir, ".vars"),
      `PORT  z.coerce.number()\n  @prod = ${encPort}\n`,
    );

    const result = generateExport(join(tmpDir, ".vars"), "prod", key);
    expect(result).toContain("PORT=8080");
  });

  it("uses @default when specific env not found", () => {
    writeFileSync(
      join(tmpDir, ".vars"),
      "PORT  z.coerce.number()\n  @default = 3000\n",
    );

    const result = generateExport(join(tmpDir, ".vars"), "staging", null);
    expect(result).toContain("PORT=3000");
  });

  it("omits variables with no value for the given env", () => {
    writeFileSync(
      join(tmpDir, ".vars"),
      "PROD_ONLY  z.string()\n  @prod = value\n",
    );

    const result = generateExport(join(tmpDir, ".vars"), "dev", null);
    expect(result).not.toContain("PROD_ONLY");
  });

  it("includes header comment with vars export", () => {
    writeFileSync(
      join(tmpDir, ".vars"),
      "PORT  z.coerce.number()\n  @default = 3000\n",
    );

    const result = generateExport(join(tmpDir, ".vars"), "dev", null);
    expect(result).toContain("# Generated by 'vars export --env dev'");
  });

  it("quotes values containing spaces", () => {
    writeFileSync(
      join(tmpDir, ".vars"),
      "MSG  z.string()\n  @default = hello world\n",
    );

    const result = generateExport(join(tmpDir, ".vars"), "dev", null);
    expect(result).toContain('MSG="hello world"');
  });

  it("skips encrypted values when no key is provided", () => {
    const enc = encrypt("secret", key);
    writeFileSync(
      join(tmpDir, ".vars"),
      `SECRET  z.string()\n  @dev = ${enc}\n`,
    );

    const result = generateExport(join(tmpDir, ".vars"), "dev", null);
    expect(result).not.toContain("SECRET");
  });
});

describe("listEnvironments", () => {
  let tmpDir: string;
  let key: Buffer;

  beforeEach(() => {
    tmpDir = mkdtempSync(join(tmpdir(), "vars-listenv-test-"));
    key = randomBytes(32);
  });

  it("lists all unique environments, sorted, excluding default", () => {
    writeFileSync(
      join(tmpDir, ".vars"),
      [
        "PORT  z.coerce.number()",
        "  @default = 3000",
        "  @dev     = 3000",
        "  @prod    = 8080",
        "  @staging = 4000",
        "",
        "HOST  z.string()",
        "  @dev  = localhost",
        "  @prod = example.com",
      ].join("\n"),
    );

    const envs = listEnvironments(join(tmpDir, ".vars"));
    expect(envs).toEqual(["dev", "prod", "staging"]);
  });

  it("discovers environments even when values are encrypted", () => {
    const enc = encrypt("secret", key);
    writeFileSync(
      join(tmpDir, ".vars"),
      `SECRET  z.string()\n  @prod = ${enc}\n`,
    );

    const envs = listEnvironments(join(tmpDir, ".vars"));
    expect(envs).toEqual(["prod"]);
  });

  it("returns empty array when no environments defined", () => {
    writeFileSync(
      join(tmpDir, ".vars"),
      "PORT  z.coerce.number()\n  @default = 3000\n",
    );

    const envs = listEnvironments(join(tmpDir, ".vars"));
    expect(envs).toEqual([]);
  });
});
