import { mkdtempSync, writeFileSync, readFileSync, existsSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, expect, it, beforeEach } from "vitest";
import { initProject, inferSchema, scanEnvFile } from "../../commands/init.js";

describe("vars init", () => {
  let tmpDir: string;

  beforeEach(() => {
    tmpDir = mkdtempSync(join(tmpdir(), "vars-init-test-"));
  });

  describe("scanEnvFile", () => {
    it("reads key-value pairs from a .env file", () => {
      writeFileSync(join(tmpDir, ".env"), "PORT=3000\nHOST=localhost\n");
      const vars = scanEnvFile(join(tmpDir, ".env"));
      expect(vars).toEqual([
        { name: "PORT", value: "3000" },
        { name: "HOST", value: "localhost" },
      ]);
    });

    it("skips comments and empty lines", () => {
      writeFileSync(join(tmpDir, ".env"), "# comment\n\nPORT=3000\n");
      const vars = scanEnvFile(join(tmpDir, ".env"));
      expect(vars).toHaveLength(1);
    });

    it("handles values with = signs", () => {
      writeFileSync(join(tmpDir, ".env"), "URL=postgres://host?opt=val\n");
      const vars = scanEnvFile(join(tmpDir, ".env"));
      expect(vars[0].value).toBe("postgres://host?opt=val");
    });

    it("strips surrounding quotes", () => {
      writeFileSync(join(tmpDir, ".env"), 'SECRET="my secret"\n');
      const vars = scanEnvFile(join(tmpDir, ".env"));
      expect(vars[0].value).toBe("my secret");
    });
  });

  describe("inferSchema", () => {
    it("infers z.string().url() for URL values", () => {
      expect(inferSchema("DATABASE_URL", "postgres://localhost:5432/db")).toBe(
        "z.string().url()",
      );
    });

    it("infers z.coerce.number() for numeric values", () => {
      expect(inferSchema("PORT", "3000")).toBe("z.coerce.number()");
    });

    it("infers z.coerce.boolean() for boolean values", () => {
      expect(inferSchema("DEBUG", "true")).toBe("z.coerce.boolean()");
      expect(inferSchema("VERBOSE", "false")).toBe("z.coerce.boolean()");
    });

    it("infers z.string() for plain strings", () => {
      expect(inferSchema("API_KEY", "sk_test_abc123")).toBe("z.string()");
    });

    it("infers z.string().url() for https URLs", () => {
      expect(inferSchema("ENDPOINT", "https://api.example.com")).toBe(
        "z.string().url()",
      );
    });

    it("infers z.enum() for common enum patterns", () => {
      expect(inferSchema("LOG_LEVEL", "info")).toBe(
        'z.enum(["debug", "info", "warn", "error"])',
      );
      expect(inferSchema("NODE_ENV", "production")).toBe(
        'z.enum(["development", "staging", "production", "test"])',
      );
    });
  });

  describe("initProject", () => {
    it("creates .vars and .vars.key from .env", async () => {
      writeFileSync(join(tmpDir, ".env"), "PORT=3000\nHOST=localhost\n");

      await initProject({
        cwd: tmpDir,
        pin: "1234",
        env: "dev",
        interactive: false,
      });

      expect(existsSync(join(tmpDir, ".vars"))).toBe(true);
      expect(existsSync(join(tmpDir, ".vars.key"))).toBe(true);
    });

    it("generated .vars has encrypted values", async () => {
      writeFileSync(join(tmpDir, ".env"), "PORT=3000\n");

      await initProject({
        cwd: tmpDir,
        pin: "1234",
        env: "dev",
        interactive: false,
      });

      const content = readFileSync(join(tmpDir, ".vars"), "utf8");
      expect(content).toContain("PORT");
      expect(content).toContain("enc:v1:aes256gcm:");
    });

    it("generated .vars.key is PIN-encrypted", async () => {
      writeFileSync(join(tmpDir, ".env"), "PORT=3000\n");

      await initProject({
        cwd: tmpDir,
        pin: "1234",
        env: "dev",
        interactive: false,
      });

      const keyContent = readFileSync(join(tmpDir, ".vars.key"), "utf8").trim();
      expect(keyContent).toMatch(/^pin:v1:aes256gcm:/);
    });

    it("creates .vars even without existing .env (empty project)", async () => {
      await initProject({
        cwd: tmpDir,
        pin: "5678",
        env: "dev",
        interactive: false,
      });

      expect(existsSync(join(tmpDir, ".vars"))).toBe(true);
      expect(existsSync(join(tmpDir, ".vars.key"))).toBe(true);
      const content = readFileSync(join(tmpDir, ".vars"), "utf8");
      expect(content).toContain("# Generated by vars init");
    });

    it("appends to .gitignore", async () => {
      writeFileSync(join(tmpDir, ".gitignore"), "node_modules/\n");

      await initProject({
        cwd: tmpDir,
        pin: "1234",
        env: "dev",
        interactive: false,
      });

      const gitignore = readFileSync(join(tmpDir, ".gitignore"), "utf8");
      expect(gitignore).toContain(".vars.key");
      expect(gitignore).toContain(".env");
      expect(gitignore).toContain("node_modules/");
    });
  });
});
