import type { VarsFile, Variable } from "./types.js";

export function generateTypes(varsFile: VarsFile, envFile = ".vars"): string {
  const lines: string[] = [];

  lines.push("// env.generated.ts (auto-generated by vars — do not edit)");
  lines.push('import { z } from "zod";');
  lines.push('import { loadEnvx, Redacted } from "@vars/core";');
  lines.push("");

  // Schema object
  lines.push("const schema = z.object({");
  for (const v of varsFile.variables) {
    lines.push(`  ${v.name}: ${v.schema},`);
  }
  lines.push("});");
  lines.push("");

  // Env type
  lines.push("export type Env = {");
  for (const v of varsFile.variables) {
    const optional = v.schema.includes(".optional()");
    const tsType = inferTsType(v);
    const key = optional ? `${v.name}?` : v.name;
    lines.push(`  ${key}: ${tsType};`);
  }
  lines.push("};");
  lines.push("");

  // Server env export
  lines.push(`export const env: Env = loadEnvx("${envFile}", {`);
  lines.push('  env: process.env.VARS_ENV || "development",');
  lines.push("  schema,");
  lines.push("});");
  lines.push("");

  // Client env export (PUBLIC_* and NEXT_PUBLIC_* variables only)
  const clientVars = varsFile.variables.filter(
    (v) => v.name.startsWith("PUBLIC_") || v.name.startsWith("NEXT_PUBLIC_"),
  );
  if (clientVars.length > 0) {
    const pickKeys = clientVars.map((v) => `"${v.name}"`).join(" | ");
    lines.push(`export const clientEnv: Pick<Env, ${pickKeys}> = {`);
    for (const v of clientVars) {
      lines.push(`  ${v.name}: env.${v.name},`);
    }
    lines.push("};");
    lines.push("");
  }

  return lines.join("\n");
}

function inferTsType(variable: Variable): string {
  const schema = variable.schema;

  // Number types
  if (schema.includes("z.number()") || schema.includes("z.coerce.number()")) {
    return "number";
  }

  // Boolean types
  if (schema.includes("z.boolean()") || schema.includes("z.coerce.boolean()")) {
    return "boolean";
  }

  // Enum types — extract literal union
  const enumMatch = schema.match(/z\.enum\(\[([^\]]+)\]\)/);
  if (enumMatch) {
    return enumMatch[1]
      .split(",")
      .map((s) => s.trim())
      .join(" | ");
  }

  // String types → Redacted<string>
  return "Redacted<string>";
}
