import type { VarsFile, Variable } from "./types.js";

export function generateTypes(varsFile: VarsFile, envFile = ".vars"): string {
  const lines: string[] = [];

  lines.push("// vars.generated.ts (auto-generated by vars — do not edit)");
  lines.push('import { z } from "zod";');
  lines.push('import { Redacted } from "@vars/core";');
  lines.push("");

  // env-aware boolean coercion (handles "false", "0", "" correctly)
  lines.push("const FALSY = new Set([\"false\", \"0\", \"\"]);");
  lines.push("const envBoolean = () =>");
  lines.push("  z.preprocess(");
  lines.push("    (v) => (typeof v === \"string\" ? !FALSY.has((v as string).toLowerCase().trim()) : Boolean(v)),");
  lines.push("    z.boolean(),");
  lines.push("  );");
  lines.push("");

  // Schema object
  lines.push("export const schema = z.object({");
  for (const v of varsFile.variables) {
    const schemaExpr = v.schema.includes("z.coerce.boolean()")
      ? v.schema.replaceAll("z.coerce.boolean()", "envBoolean()")
      : v.schema;
    lines.push(`  ${v.name}: ${schemaExpr},`);
  }
  lines.push("});");
  lines.push("");

  // Env type — wrap only plain string fields with Redacted (not enums, numbers, booleans)
  lines.push("export type Env = {");
  for (const v of varsFile.variables) {
    const optional = v.schema.includes(".optional()");
    const tsType = inferTsType(v);
    const key = optional ? `${v.name}?` : v.name;
    lines.push(`  ${key}: ${tsType};`);
  }
  lines.push("};");
  lines.push("");

  // Parse helper — validates + wraps plain strings in Redacted
  lines.push("function parseEnv(input: Record<string, unknown>): Env {");
  lines.push("  const parsed = schema.parse(input);");
  lines.push("  return {");
  for (const v of varsFile.variables) {
    const optional = v.schema.includes(".optional()");
    if (isSecretStringType(v)) {
      if (optional) {
        lines.push(`    ${v.name}: parsed.${v.name} != null ? new Redacted(parsed.${v.name}) : undefined,`);
      } else {
        lines.push(`    ${v.name}: new Redacted(parsed.${v.name}),`);
      }
    } else {
      lines.push(`    ${v.name}: parsed.${v.name},`);
    }
  }
  lines.push("  } as Env;");
  lines.push("}");
  lines.push("");

  // Server env export
  lines.push("export const env: Env = parseEnv(process.env);");
  lines.push("");

  // Client env export (PUBLIC_* and NEXT_PUBLIC_* variables only)
  const clientVars = varsFile.variables.filter(
    (v) => v.name.startsWith("PUBLIC_") || v.name.startsWith("NEXT_PUBLIC_"),
  );
  if (clientVars.length > 0) {
    const pickKeys = clientVars.map((v) => `"${v.name}"`).join(" | ");
    lines.push(`export const clientSchema = schema.pick({`);
    for (const v of clientVars) {
      lines.push(`  ${v.name}: true,`);
    }
    lines.push("});");
    lines.push(`export type ClientEnv = Pick<Env, ${pickKeys}>;`);

    // Parse only client vars — server-only vars may not exist in client builds
    lines.push("function parseClientEnv(input: Record<string, unknown>): ClientEnv {");
    lines.push("  const parsed = clientSchema.parse(input);");
    lines.push("  return {");
    for (const v of clientVars) {
      const optional = v.schema.includes(".optional()");
      if (isSecretStringType(v)) {
        if (optional) {
          lines.push(`    ${v.name}: parsed.${v.name} != null ? new Redacted(parsed.${v.name}) : undefined,`);
        } else {
          lines.push(`    ${v.name}: new Redacted(parsed.${v.name}),`);
        }
      } else {
        lines.push(`    ${v.name}: parsed.${v.name},`);
      }
    }
    lines.push("  } as ClientEnv;");
    lines.push("}");

    lines.push("export const clientEnv: ClientEnv = parseClientEnv(process.env);");
    lines.push("");
  }

  return lines.join("\n");
}

function inferTsType(variable: Variable): string {
  const schema = variable.schema;

  // Number types
  if (schema.includes("z.number()") || schema.includes("z.coerce.number()")) {
    return "number";
  }

  // Boolean types
  if (schema.includes("z.boolean()") || schema.includes("z.coerce.boolean()")) {
    return "boolean";
  }

  // Enum types — bare literal union (not secrets)
  const enumMatch = schema.match(/z\.enum\(\[([^\]]+)\]\)/);
  if (enumMatch) {
    return enumMatch[1]
      .split(",")
      .map((s) => s.trim())
      .join(" | ");
  }

  // Plain string types — wrapped in Redacted
  return "Redacted<string>";
}

/** Returns true for plain string types that should be wrapped in Redacted.
 *  Enums, numbers, and booleans are not secrets. */
function isSecretStringType(variable: Variable): boolean {
  const schema = variable.schema;
  if (schema.includes("z.number()") || schema.includes("z.coerce.number()")) return false;
  if (schema.includes("z.boolean()") || schema.includes("z.coerce.boolean()")) return false;
  if (schema.match(/z\.enum\(/)) return false;
  return true;
}
