import {
	type GroupedVars,
	REDACTED_CLASS,
	generateSchemaBlock,
	generateVarsType,
	groupVars,
	inferType,
} from "./codegen.js";
import type { ResolvedVar, ResolvedVars } from "./types.js";

/**
 * Build the serverless `#vars` module source.
 *
 * Assumes every env in `byEnv` declares the same set of variables. The first
 * env is used as the structural reference for grouping; secret values are
 * collected per-env. Public variables are emitted as per-env leaves and are
 * selected at runtime with VARS_ENV before schema validation.
 */
export function generateServerless(byEnv: Record<string, ResolvedVars>): string {
	const envNames = Object.keys(byEnv);
	if (envNames.length === 0) throw new Error("generateServerless: no envs provided");

	const ref = byEnv[envNames[0]];
	const grouped = groupVars(ref.vars);

	const lines: string[] = [];

	// Header + imports + Redacted class + schema + Vars type.
	lines.push("// @generated by vars — do not edit");
	lines.push("// @vars-platform: serverless");
	lines.push("import { z } from 'zod';");
	lines.push("");
	lines.push(REDACTED_CLASS);
	lines.push("");
	lines.push(generateSchemaBlock(grouped));
	lines.push("");
	lines.push(generateVarsType(grouped));
	lines.push("");

	// PUBLIC_VARS — nested to mirror the schema shape. Public leaves are keyed
	// by env so serverless output can support public config that differs
	// between dev/prod without requiring decryption.
	lines.push("const PUBLIC_VARS = {");
	for (const v of grouped.topLevel) {
		if (!v.public) continue;
		lines.push(`  ${v.name}: ${formatEnvValueMap(v, byEnv, 2)},`);
	}
	for (const [groupName, groupVars] of grouped.groups) {
		const publicMembers = groupVars.filter((m) => m.public);
		if (publicMembers.length === 0) continue;
		lines.push(`  ${groupName}: {`);
		for (const v of publicMembers) {
			lines.push(`    ${v.name}: ${formatEnvValueMap(v, byEnv, 4)},`);
		}
		lines.push("  },");
	}
	lines.push("} as const;");
	lines.push("");

	// CIPHERTEXTS — nested per env so grouped secrets round-trip through
	// the schema without flattening (which would collide with the nested
	// z.object() groups).
	lines.push("const CIPHERTEXTS = {");
	for (const env of envNames) {
		lines.push(`  ${JSON.stringify(env)}: {`);
		for (const v of grouped.topLevel) {
			if (v.public) continue;
			const val = byEnv[env].vars.find((x) => x.name === v.name && !x.group)?.value;
			lines.push(`    ${v.name}: ${JSON.stringify(val ?? "")},`);
		}
		for (const [groupName, groupVars] of grouped.groups) {
			const secretMembers = groupVars.filter((m) => !m.public);
			if (secretMembers.length === 0) continue;
			lines.push(`    ${groupName}: {`);
			for (const v of secretMembers) {
				const val = byEnv[env].vars.find((x) => x.name === v.name && x.group === groupName)?.value;
				lines.push(`      ${v.name}: ${JSON.stringify(val ?? "")},`);
			}
			lines.push("    },");
		}
		lines.push("  },");
	}
	lines.push("} as const;");

	lines.push("");
	lines.push(EMBEDDED_CRYPTO_HELPERS);

	lines.push("");
	lines.push(generateWrapRedacted(grouped));

	const envUnion = envNames.map((e) => JSON.stringify(e)).join(" | ");
	lines.push(`
const cache = new Map<string, Promise<Vars>>();

export async function getVars(
  env: { VARS_KEY?: string; VARS_ENV?: string } & Record<string, unknown>,
  envOverride?: ${envUnion},
): Promise<Vars> {
  const targetEnv = envOverride ?? (env.VARS_ENV as ${envUnion} | undefined);
  if (!targetEnv) throw new Error("vars: VARS_ENV not set and no override passed");
  if (!(targetEnv in CIPHERTEXTS)) throw new Error("vars: unknown env \\\"" + targetEnv + "\\\"");
  if (!env.VARS_KEY) throw new Error("vars: VARS_KEY not set in runtime env");
  const cacheKey = targetEnv + ":" + env.VARS_KEY;
  const hit = cache.get(cacheKey);
  if (hit) return hit;
  const inflight = (async () => {
    const masterKey = base64ToBytes(env.VARS_KEY as string);
    const raw: Record<string, unknown> = {};
    for (const [k, v] of Object.entries(PUBLIC_VARS)) {
      raw[k] = selectPublicValue(v, targetEnv);
    }
    const envCiphers = CIPHERTEXTS[targetEnv] as Record<string, string | Record<string, string>>;
    for (const [name, value] of Object.entries(envCiphers)) {
      if (typeof value === "string") {
        raw[name] = await decryptToken(value, masterKey);
      } else {
        const sub = (raw[name] as Record<string, string> | undefined) ?? {};
        for (const [member, token] of Object.entries(value)) {
          sub[member] = await decryptToken(token, masterKey);
        }
        raw[name] = sub;
      }
    }
    const parsed = schema.parse(raw);
    return wrapRedacted(parsed);
  })();
  cache.set(cacheKey, inflight);
  inflight.catch(() => {
    if (cache.get(cacheKey) === inflight) cache.delete(cacheKey);
  });
  return inflight;
}
`);

	return lines.join("\n");
}

function formatEnvValueMap(
	v: ResolvedVar,
	byEnv: Record<string, ResolvedVars>,
	indent: number,
): string {
	const pad = " ".repeat(indent);
	const entries: string[] = [];
	for (const env of Object.keys(byEnv)) {
		const match = byEnv[env].vars.find((x) => x.name === v.name && x.group === v.group);
		entries.push(`${pad}  ${JSON.stringify(env)}: ${JSON.stringify(match?.value)},`);
	}
	return `{\n${entries.join("\n")}\n${pad}}`;
}

function generateWrapRedacted(grouped: GroupedVars): string {
	const lines: string[] = [];
	lines.push("function wrapRedacted(parsed: Record<string, unknown>): Vars {");
	lines.push("  return {");

	// Top-level
	for (const v of grouped.topLevel) {
		const inf = inferType(v);
		if (inf.needsRedacted) {
			lines.push(`    ${v.name}: new Redacted(parsed.${v.name} as string),`);
		} else {
			lines.push(`    ${v.name}: parsed.${v.name} as ${inf.base},`);
		}
	}

	// Groups
	for (const [groupName, vars] of grouped.groups) {
		lines.push(`    ${groupName}: {`);
		for (const v of vars) {
			const inf = inferType(v);
			const accessor = `(parsed.${groupName} as Record<string, unknown>)`;
			if (inf.needsRedacted) {
				lines.push(`      ${v.name}: new Redacted(${accessor}.${v.name} as string),`);
			} else {
				lines.push(`      ${v.name}: ${accessor}.${v.name} as ${inf.base},`);
			}
		}
		lines.push("    },");
	}

	lines.push("  };");
	lines.push("}");
	return lines.join("\n");
}

const EMBEDDED_CRYPTO_HELPERS = `
function base64ToBytes(b64: string): Uint8Array {
  const bin = typeof atob === "function" ? atob(b64) : Buffer.from(b64, "base64").toString("binary");
  const out = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
  return out;
}

async function hkdfSha256(master: Uint8Array, salt: string, info: string, length: number): Promise<Uint8Array> {
  const saltBytes = new TextEncoder().encode(salt);
  const infoBytes = new TextEncoder().encode(info);
  const baseKey = await crypto.subtle.importKey("raw", master as BufferSource, "HKDF", false, ["deriveBits"]);
  const bits = await crypto.subtle.deriveBits(
    { name: "HKDF", hash: "SHA-256", salt: saltBytes, info: infoBytes },
    baseKey,
    length * 8,
  );
  return new Uint8Array(bits);
}

async function decryptToken(token: string, masterKey: Uint8Array): Promise<string> {
  const PREFIX = "enc:v2:aes256gcm-det:";
  if (!token.startsWith(PREFIX)) throw new Error("vars: invalid token format");
  const rest = token.slice(PREFIX.length);
  const parts = rest.split(":");
  let owner: string | null = null;
  let iv: string;
  let ct: string;
  let tag: string;
  if (parts.length === 4 && parts[0]!.startsWith("owner=")) {
    owner = parts[0]!.slice("owner=".length);
    iv = parts[1]!;
    ct = parts[2]!;
    tag = parts[3]!;
  } else if (parts.length === 3) {
    iv = parts[0]!;
    ct = parts[1]!;
    tag = parts[2]!;
  } else {
    throw new Error("vars: malformed token");
  }
  let aesKey = masterKey;
  if (owner) aesKey = await hkdfSha256(masterKey, "dotvars-owner-key-v1", "owner:" + owner, 32);
  const key = await crypto.subtle.importKey("raw", aesKey as BufferSource, { name: "AES-GCM" }, false, ["decrypt"]);
  const ivBytes = base64ToBytes(iv);
  const ctBytes = base64ToBytes(ct);
  const tagBytes = base64ToBytes(tag);
  const combined = new Uint8Array(ctBytes.length + tagBytes.length);
  combined.set(ctBytes, 0);
  combined.set(tagBytes, ctBytes.length);
  try {
    const pt = await crypto.subtle.decrypt({ name: "AES-GCM", iv: ivBytes as BufferSource }, key, combined as BufferSource);
    return new TextDecoder().decode(pt);
  } catch {
    throw new Error("vars: decryption failed — wrong VARS_KEY or tampered ciphertext");
  }
}

function selectPublicValue(value: unknown, targetEnv: string): unknown {
  if (!value || typeof value !== "object") return value;
  const obj = value as Record<string, unknown>;
  if (Object.prototype.hasOwnProperty.call(obj, targetEnv)) return obj[targetEnv];
  const out: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(obj)) {
    out[k] = selectPublicValue(v, targetEnv);
  }
  return out;
}
`;
