import { describe, it, expect } from "vitest";
import { generateTypeScript } from "../codegen.js";
import type { ResolvedVars } from "../types.js";

function makeResolved(vars: Partial<import("../types.js").ResolvedVar>[]): ResolvedVars {
  return {
    vars: vars.map(v => ({
      name: v.name ?? "X",
      flatName: v.flatName ?? v.name ?? "X",
      public: v.public ?? false,
      schema: v.schema ?? "z.string()",
      value: v.value,
      metadata: v.metadata ?? null,
      group: v.group,
    })),
    checks: [],
    envs: ["dev", "prod"],
    params: [],
    sourceFiles: ["config.vars"],
  };
}

describe("codegen", () => {
  it("generates @generated header with source hash", () => {
    const code = generateTypeScript(makeResolved([
      { name: "X", public: true, schema: "z.string()", value: "hello" },
    ]));
    expect(code).toContain("@generated by vars");
    expect(code).toContain("@vars-source-hash:");
  });

  it("generates Redacted class inline", () => {
    const code = generateTypeScript(makeResolved([
      { name: "SECRET", schema: "z.string()", value: "x" },
    ]));
    expect(code).toContain("class Redacted<T>");
    expect(code).toContain("unwrap()");
    expect(code).toContain("<redacted>");
  });

  it("types public string as plain string", () => {
    const code = generateTypeScript(makeResolved([
      { name: "APP_NAME", public: true, schema: "z.string()", value: "app" },
    ]));
    expect(code).toContain("APP_NAME: string");
    expect(code).not.toMatch(/APP_NAME: Redacted/);
  });

  it("types public number as number", () => {
    const code = generateTypeScript(makeResolved([
      { name: "PORT", public: true, schema: "z.number()", value: "3000" },
    ]));
    expect(code).toContain("PORT: number");
  });

  it("types public enum as literal union", () => {
    const code = generateTypeScript(makeResolved([
      { name: "LOG", public: true, schema: 'z.enum(["debug", "info", "warn"])', value: "info" },
    ]));
    expect(code).toMatch(/LOG: "debug" \| "info" \| "warn"/);
  });

  it("types secret string as Redacted<string>", () => {
    const code = generateTypeScript(makeResolved([
      { name: "DB_URL", public: false, schema: "z.string().url()", value: "x" },
    ]));
    expect(code).toContain("DB_URL: Redacted<string>");
  });

  it("types secret number as plain number (deliberate)", () => {
    const code = generateTypeScript(makeResolved([
      { name: "SECRET_PORT", public: false, schema: "z.number()", value: "3000" },
    ]));
    expect(code).toContain("SECRET_PORT: number");
    expect(code).not.toMatch(/SECRET_PORT: Redacted/);
  });

  it("types secret boolean as plain boolean (deliberate)", () => {
    const code = generateTypeScript(makeResolved([
      { name: "SECRET_FLAG", public: false, schema: "z.boolean()", value: "true" },
    ]));
    expect(code).toContain("SECRET_FLAG: boolean");
    expect(code).not.toMatch(/SECRET_FLAG: Redacted/);
  });

  it("generates nested types for groups", () => {
    const code = generateTypeScript(makeResolved([
      { name: "SECRET_KEY", flatName: "STRIPE_SECRET_KEY", public: false, schema: "z.string()", value: "sk", group: "stripe" },
      { name: "PUB_KEY", flatName: "STRIPE_PUB_KEY", public: true, schema: "z.string()", value: "pk", group: "stripe" },
    ]));
    expect(code).toContain("stripe:");
    expect(code).toContain("SECRET_KEY: Redacted<string>");
    expect(code).toContain("PUB_KEY: string");
  });

  it("generates ClientVars with only public vars", () => {
    const code = generateTypeScript(makeResolved([
      { name: "PUBLIC_VAR", public: true, schema: "z.string()", value: "x" },
      { name: "SECRET_VAR", public: false, schema: "z.string()", value: "y" },
    ]));
    expect(code).toContain("ClientVars");
    expect(code).toMatch(/ClientVars.*PUBLIC_VAR/s);
  });

  it("generates process.env for default (node) platform", () => {
    const code = generateTypeScript(makeResolved([
      { name: "X", public: true, schema: "z.string()", value: "v" },
    ]));
    expect(code).toContain("process.env");
  });

  it("generates getVars function for cloudflare platform", () => {
    const code = generateTypeScript(makeResolved([
      { name: "X", public: true, schema: "z.string()", value: "v" },
    ]), { platform: "cloudflare" });
    expect(code).toContain("getVars");
    expect(code).not.toContain("process.env");
  });

  it("generates Deno.env for deno platform", () => {
    const code = generateTypeScript(makeResolved([
      { name: "X", public: true, schema: "z.string()", value: "v" },
    ]), { platform: "deno" });
    expect(code).toContain("Deno.env");
  });

  it("generates inlined values for static platform", () => {
    const code = generateTypeScript(makeResolved([
      { name: "APP", public: true, schema: "z.string()", value: "my-app" },
      { name: "SECRET", public: false, schema: "z.string()", value: "s3cret" },
    ]), { platform: "static" });
    expect(code).toContain('"my-app"');
    expect(code).toContain("new Redacted");
    expect(code).not.toContain("process.env");
    expect(code).not.toContain("parseVars");
  });

  it("handles optional schema", () => {
    const code = generateTypeScript(makeResolved([
      { name: "OPT", public: true, schema: "z.string().optional()", value: undefined },
    ]));
    expect(code).toMatch(/OPT\??: string/);
  });

  it("does not generate broken clientVars for cloudflare platform", () => {
    const code = generateTypeScript(makeResolved([
      { name: "PUB", public: true, schema: "z.string()", value: "x" },
      { name: "SEC", public: false, schema: "z.string()", value: "y" },
    ]), { platform: "cloudflare" });
    // Should not reference a non-existent vars constant
    expect(code).not.toMatch(/const clientVars.*=.*\bvars\./);
  });
});
