import { mkdirSync, realpathSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { findOrphanedServerlessBundles } from "../commands/doctor.js";

function makeTmpDir(): string {
	const dir = join(tmpdir(), `doctor-${Date.now()}-${Math.random().toString(36).slice(2)}`);
	mkdirSync(dir, { recursive: true });
	return realpathSync(dir);
}

describe("findOrphanedServerlessBundles", () => {
	let tmp: string;

	beforeEach(() => {
		tmp = makeTmpDir();
	});

	afterEach(() => {
		rmSync(tmp, { recursive: true, force: true });
		vi.unstubAllEnvs();
	});

	it("returns empty when VARS_KEY is a valid 32-byte key", () => {
		vi.stubEnv("VARS_KEY", Buffer.alloc(32).toString("base64"));
		const varsPath = join(tmp, "config.vars");
		const generatedPath = join(tmp, "config.generated.ts");
		writeFileSync(varsPath, "env(dev)\n");
		writeFileSync(
			generatedPath,
			"// @generated by vars — do not edit\n// @vars-platform: serverless\n",
		);
		expect(findOrphanedServerlessBundles(tmp)).toEqual([]);
	});

	it("does not accept a malformed VARS_KEY", () => {
		vi.stubEnv("VARS_KEY", "xxx");
		writeFileSync(join(tmp, "config.vars"), "env(dev)\n");
		writeFileSync(join(tmp, "config.generated.ts"), "// @vars-platform: serverless\n");
		expect(findOrphanedServerlessBundles(tmp)).toEqual(["config.generated.ts"]);
	});

	it("returns empty when there are no .vars files", () => {
		vi.stubEnv("VARS_KEY", "");
		expect(findOrphanedServerlessBundles(tmp)).toEqual([]);
	});

	it("returns empty when a .vars has a .generated.ts without the marker", () => {
		vi.stubEnv("VARS_KEY", "");
		const varsPath = join(tmp, "config.vars");
		const generatedPath = join(tmp, "config.generated.ts");
		writeFileSync(varsPath, "env(dev)\n");
		writeFileSync(generatedPath, "// @generated by vars — do not edit\nexport const vars = {};\n");
		expect(findOrphanedServerlessBundles(tmp)).toEqual([]);
	});

	it("returns empty when a .vars has no .generated.ts sibling", () => {
		vi.stubEnv("VARS_KEY", "");
		writeFileSync(join(tmp, "config.vars"), "env(dev)\n");
		expect(findOrphanedServerlessBundles(tmp)).toEqual([]);
	});

	it("returns the relative path when marker is present and VARS_KEY is unset", () => {
		vi.stubEnv("VARS_KEY", "");
		const varsPath = join(tmp, "config.vars");
		const generatedPath = join(tmp, "config.generated.ts");
		writeFileSync(varsPath, "env(dev)\n");
		writeFileSync(
			generatedPath,
			"// @generated by vars — do not edit\n// @vars-platform: serverless\nexport const x = 1;\n",
		);
		const hits = findOrphanedServerlessBundles(tmp);
		expect(hits).toEqual(["config.generated.ts"]);
	});

	it("reports the bundle once when both .vars and .unlocked.vars exist", () => {
		vi.stubEnv("VARS_KEY", "");
		const varsPath = join(tmp, "config.vars");
		const unlockedPath = join(tmp, "config.unlocked.vars");
		const generatedPath = join(tmp, "config.generated.ts");
		writeFileSync(varsPath, "env(dev)\n");
		writeFileSync(unlockedPath, "env(dev)\n");
		writeFileSync(
			generatedPath,
			"// @generated by vars — do not edit\n// @vars-platform: serverless\n",
		);
		const hits = findOrphanedServerlessBundles(tmp);
		expect(hits).toEqual(["config.generated.ts"]);
	});

	it("finds bundles in nested directories", () => {
		vi.stubEnv("VARS_KEY", "");
		const nested = join(tmp, "apps", "api");
		mkdirSync(nested, { recursive: true });
		const varsPath = join(nested, "config.vars");
		const generatedPath = join(nested, "config.generated.ts");
		writeFileSync(varsPath, "env(dev)\n");
		writeFileSync(
			generatedPath,
			"// @generated by vars — do not edit\n// @vars-platform: serverless\n",
		);
		const hits = findOrphanedServerlessBundles(tmp);
		expect(hits).toEqual([join("apps", "api", "config.generated.ts")]);
	});
});
